### ISSUE TITLE
Searching on 440i returns mainly 330 results

### ISSUE THREAD

**Issue by AndieNarwhal** [clasys/CarScrapper#4]
<img width="1432" alt="Screen Shot 2020-07-05 at 09 11 39" src="https://user-images.githubusercontent.com/5289026/86537312-1fc25e80-bea3-11ea-999d-5af1072b1eea.png">

**Comment by clasys** [comment]
Seems to be due to three of newly added DealerCom dealers being incompatible with generic DealerCom search:
https://www.bmwofbeverlyhills.com
https://www.longbeachbmw.com
https://www.bmwofmonrovia.net

Instead of expected URL structure 

> www.dealername.com/new-inventory/index.htm?model={modelName} 

they have custom URL. For example, 

> https://www.bmwofmonrovia.net/new-bmw/monrovia.htm?model={modelName}

Hitting expected URL returns all models, which then pollutes search results in the grid with non-related model results.

Possible fixes:
remove from config as not compatible for now
add generic code to custom handle URLs for specific dealers, with custom URL structure coming from config entry for a specific dealer (look into how much effort this might be, could be beneficial for other ouliers in the future)

**Comment by clasys** [comment]
Added code to support custom URLs for dealers whose URLs differ from all other.
